import TechnologiesPage from "@/components/TechnologiesPage";
import Head from "next/head";

export default function Techs(){

  return(
    <>
    <Head>
      <title>Juliu Cesar</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/jc-icon.ico" />
    </Head>
    <TechnologiesPage />
  </>
  )
}